### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Delice0** [TheBlob42/idea-which-key#44] opened 2023-10-04 14:53 UTC
I installed plugins: IdeaVim and Which-Key through Intellij.

I added 'set which-key' inside .ideavimrc in my home dir.

I sourced .ideavimrc.

Nothing happens when pressing space.

**Comment by TheBlob42** [comment] 2023-10-06 08:14
I would need some more information about your setup to check for any issues:
Intellij version, IdeaVim version, WhichKey version and your `.ideavimrc` configuration

**Comment by kangxiaoning** [comment] 2023-10-09 06:38
I'm using CLion 2023.2.2 on Windows, having installed `ideavim`, `which-key`, and configured `intellimacs`, it seems nothing happens after pressing space.

which-key version: 0.8.0
ideavim version: 2.5.1/2.0.0

The following is my `.ideavimre` file placed in the `%USERPROFILE%` directory.

```
source ~/.intellimacs/spacemacs.vim

" (Optional) Enable other Intellimacs modules
source ~/.intellimacs/extra.vim
source ~/.intellimacs/major.vim
source ~/.intellimacs/hybrid.vim

" (Optional) Enable which-key plugin
source ~/.intellimacs/which-key.vim

" (Optional) My own vim commands
nnoremap Y y$

" (Optional) Comma for major mode
nmap , <leader>m
vmap , <leader>m

" (Optional) Add/edit actions
nnoremap <leader>gl    :action Vcs.Show.Log<CR>
vnoremap <leader>gl    :action Vcs.Show.Log<CR>
```

**Comment by Delice0** [comment] 2023-10-10 22:12
> I would need some more information about your setup to check for any issues: Intellij version, IdeaVim version, WhichKey version and your `.ideavimrc` configuration
```
IntelliJ IDEA 2023.1.5 (Community Edition)
Build #IC-231.9392.1, built on July 25, 2023
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    Docker (231.9392.1)
    IdeaVIM (2.5.1)
    DBN (3.3.9882.0)

Kotlin: 231-1.8.21-IJ9392.1
```
ideavim + whichkey latest from todays date. and .ideavimrc contains _only_ that config from your doc "set which-key" or something like that.

**Comment by TheBlob42** [comment] 2023-10-14 10:18
Please share your full `.ideavimrc` with me. In most cases this is a configuration problem, a typo or something similar (even though it does not contain a lot). 

From your system setup I don't see any reason why the plugin should not work :thinking:

**Comment by TheBlob42** [comment] 2023-10-31 05:30
@Delice0 is this issue still present? If so please share your `.ideavimrc` so I can investigate.
Otherwise I would close this issue

**Comment by clemenscodes** [comment] 2023-10-31 11:01
Having the same issue.
Tested it on windows and linux systems, and using different JBR runtimes. When I uninstall the plugin I get some logs that state that which-key is an unknown command in my `.ideavimrc`. However after installing the plugin It appears as if which-key was a noop. No logs, pressing space just moves the cursor.

My .ideavimrc:
```
set which-key
```

**Comment by TheBlob42** [comment] 2023-11-01 06:19
So I got a notification about a new comment here, which for some reason is not visible anymore:

> Having the same issue.
Tested it on windows and linux systems, and using different JBR runtimes. When I uninstall the plugin I get some logs that state that which-key is an unknown command in my .ideavimrc. However after installing the plugin It appears as if which-key was a noop. No logs, pressing space just moves the cursor.
>
> My .ideavimrc:
>
> set which-key

However I wanted to address this anyway since its the same issue as @Delice0 and I think I now finally understand what the issue is here :sweat_smile: 

It seems like there is a discrepancy for new users about what _which-key_  is actually doing and what it is **not**. So for everybody in this issue and everybody finding this let me explain:

The plugin _which-key_ is only there to showcase the VIM mappings that you have configured **yourself** (in your `.ideavimrc`) in a popup window. It does **not** set any keybindings itself. The GIF in the README is an example of how it can look in case you have a lot of mappings defined (the example uses the wonderful [intellimacs](https://github.com/MarcoIeni/intellimacs) project). It seems to me that this is a common misunderstanding (see #46), so I will adapt the README to make this distinction more clear. 

For those wondering why they see no popup, add a few key mappings to your `.ideavimrc` and try again:

```vim
set which-key

nnoremap <Space>wv :vertical splitv<CR>
nnoremap <Space>ws :split<CR>
nnoremap <Space>wd :close<CR>
```
Now pressing `<Space`> and `<Space>w` should show a popup with all the above mappings

I hope this helps :slightly_smiling_face:

**Comment by clemenscodes** [comment] 2023-11-03 10:59
Thanks! Yeah, my bad, I did assume that an empty  popup would come up if I had no keybinds set. Now this works!

**Comment by Delice0** [comment] 2023-11-03 11:25
> @Delice0 is this issue still present? If so please share your `.ideavimrc` so I can investigate. Otherwise I would close this issue

set which-key

that's it.

**Comment by TheBlob42** [comment] 2023-11-03 15:47
@Delice0 then check my previous comment https://github.com/TheBlob42/idea-which-key/issues/44#issuecomment-1788472425 for an explanation

**Closed** 2023-11-07 18:59 UTC
