### ISSUE TITLE
Erasing bindings?

### ISSUE THREAD

**Issue by quicknir** [TheBlob42/idea-which-key#18] opened 2021-11-10 19:20 UTC
It seems like many of the bindings added by plugins count as bindings added by config, as far as which-key is concerned (and not "default" bindings), so in some cases I have these default (unused) bindings showing up in which-key menus that I can't always easily remove. Is there a way to remove those entries?

**Comment by TheBlob42** [comment] 2021-11-11 21:06
You're talking about removing certain entries from being displayed in the popup BUT one could still execute them by pressing the corresponding keys. So it is just about removing a keybinding from being displayed, but not be removed/unbinded?

If you mean it this way, than there is currently no way to archive this unfortunately :slightly_frowning_face: 
I have to admit I never came across such a "situation" myself, probably because I don't have many plugins installed beside IdeaVIM. Can you name me one or more plugins which add keybindings, so I could have a closer look?

**Comment by quicknir** [comment] 2021-11-11 21:18
Correct, just removing their presence from which-key; the unbinding is a separate matter (and of course beyond the scope of which-key).

Easiest example probably is `set commentary`. This makes for example `gcc` comment out the current line. So after I hit `g`, I see an entry "c -> Prefix", and then after I hit, `c`, I see "<Plug>(CommentLine).

My idea would just be to make it so that if you set a variable to the shortcut and no following text it would remove any existing entry for that shortcut. `let g:WhichKeyDesc_foo = "gc".  But if that's too much trouble of course I understand.

**Comment by TheBlob42** [comment] 2021-11-12 11:51
Thank you for the simple example and the suggestion. I like the idea that if you don't specify any description it means you actually want the mapping to be excluded/removed from the popup. This way there would be no "special syntax" for this feature.

I will have a look into this as I believe it would not be complicated feature to implement. It might take me some days

**Comment by TheBlob42** [comment] 2021-11-13 11:38
I have just pushed the feature to the `develop` branch. You are invited to test if it works correctly yourself.

I will prepare a new release over the weekend, so beginning/mid of next week the update should also reach the JetBrains marketplace

**Comment by TheBlob42** [comment] 2021-11-14 09:49
Just realized that my PR automatically closed this issue :see_no_evil: 
Will keep this open till `0.6` is officially released via the JetBrains marketplace, so its easliy available for everyone

**Comment by quicknir** [comment] 2021-11-14 17:14
I am not much of a Java/Kotlin programmer so I'd probably have to familiarize myself with gradle before I could go about testing it manually :-). Not that I'm unwilling to do so if there are more iterations, but maybe for the first one I'll just give it a go when it lands on the marketplace?

**Comment by TheBlob42** [comment] 2021-11-14 21:11
No problem, it was just an offer :-)

For reference: You don't have to build it yourself but could just download the latest release I have uploaded [here](https://github.com/TheBlob42/idea-which-key/releases/tag/0.6) and [install it manually](https://github.com/TheBlob42/idea-which-key#manual-installation) (just skip the build part of it and instead use the release jar)

**Comment by TheBlob42** [comment] 2021-11-15 16:09
The `0.6` release landed in the marketplace :partying_face: 
If you find anything else missing or not working just write me about it.

**Closed by TheBlob42** 2021-11-15 16:09 UTC

**Comment by quicknir** [comment] 2021-11-23 19:08
Hmm, I can't seem to get this to work. I added:
```
" Erase some unwanted bindings
let g:WhichKeyDesc_erase_gc = "gc"
let g:WhichKeyDesc_erase_gcc = "gcc"
```
To my .ideavimrc. I restarted, and nada, the shortcuts are still there. My version is 0.6 released on Nov 13.

**Comment by TheBlob42** [comment] 2021-11-24 06:02
Well that is really weird. I have updated IdeaVIM and WhichKey on my work machine to the latest versions an copied your example and for me it works as intended :thinking: 

Would you share your complete `.ideavimrc` file, maybe that way I can see what is causing your trouble

**Comment by quicknir** [comment] 2021-11-24 21:40
Sure, here it is:
```
set surround
set multiple-cursors
set commentary
set incsearch
set hlsearch
set rnu
set nu
set argtextobj
set exchange
set clipboard+=unnamed
set which-key

" This is for which-key so the menu doesn't stop showing
set notimeout
" This is so that which-key doesn't pop up in cases I already know the shortcut"
let g:WhichKey_DefaultDelay = 1000
let g:WhichKey_FontFamily = "Jetbrains Mono"
let g:WhichKey_SortOrder = "by_description"
" Erase some unwanted bindings
let g:WhichKeyDesc_erase_gc = "gc"
let g:WhichKeyDesc_erase_gcc = "gcc"

let mapleader = " "

vnoremap I <esc>`<i
vnoremap A <esc>`>i
let g:argtextobj_pairs="(:),{:},<:>"
nmap <leader><Space> :action GotoAction<cr>
let g:WhichKeyDesc_action = "<leader><Space> find action"
nmap <leader>; :action GotoFile<cr>
let g:WhichKeyDesc_findfile = "<leader>; find file"
nmap <leader>/ :action FindInPath<cr>
let g:WhichKeyDesc_search_path_direct = "<leader>/ find text"
map s :action AceAction<cr>

" g is the "goto" prefix, inspired by the standard gd binding in vim
let g:WhichKeyDesc_goto = "g +goto"
nmap gd :action GotoDeclaration<cr>
let g:WhichKeyDesc_gotodef = "gd goto definition"
nmap gD :action opennInSplittedTab<cr>
let g:WhichKeyDesc_gotodefother = "gD goto definition other"
nmap gh :action SmartSearchAction<cr>
let g:WhichKeyDesc_gotohelp = "gh search help"
nmap gr :action FindUsages<cr>
let g:WhichKeyDesc_gotofind = "gr find usages"
nmap go :action FindUsagesInFile<cr>
let g:WhichKeyDesc_gotofindfind = "go find usages in file"
nmap gs :action FindInPath<cr>
let g:WhichKeyDesc_gotofindinpath = "gs find in path"
nmap ga :action CIDR.Lang.SwitchHeaderSource<cr>
let g:WhichKeyDesc_gotoheadersource = "ga header-source"

" still goto bindings, but these are a bit different because they open tool windows
" could consider relocating in the future
nmap gt :action TypeHierarchy<cr>
let g:WhichKeyDesc_gototype = "gt open type hierarchy"
nmap gi :action CIDR.Lang.ImportsHierarchy<cr>
let g:WhichKeyDesc_gotoimport = "gi open include hierarchy"
nmap gf :action CallHierarchy<cr>
let g:WhichKeyDesc_gotocallgraph = "gf open call graph"

" z is the "quick" prefix. It doesn't navigate or open tool windows, but popups
nmap zs :action FileStructurePopup<cr>
nmap zd :action QuickImplementations<cr>
nmap zh :action QuickJavaDoc<cr>
nmap zr :action ShowUsages<cr>

" f is the file prefix
let g:WhichKeyDesc_files = "<leader>f +files"
nmap <leader>ff :action ShowNavBar<cr>
let g:WhichKeyDesc_file_navbar = "<leader>ff navigation bar"
nmap <leader>fe :action ActivateProjectToolWindow<cr>
let g:WhichKeyDesc_file_explorer = "<leader>fe explorer"
nmap <leader>fs :action SaveAll<cr>
let g:WhichKeyDesc_file_save = "<leader>fs save all"
nmap <leader>fr :action RecentFiles<cr>
let g:WhichKeyDesc_file_recent = "<leader>fr recent files"
nmap <leader>fl :action RecentLocations<cr>
let g:WhichKeyDesc_file_locations = "<leader>fl recent locations"
nmap <leader>fc :e ~/.ideavimrc<cr>
let g:WhichKeyDesc_file_openconfig = "<leader>fc open ideavimrc"
nmap <leader>fC :source ~/.ideavimrc<cr>
let g:WhichKeyDesc_file_reloadconfig = "<leader>fC reload ideavimrc"

" s is the search prefix
let g:WhichKeyDesc_search = "<leader>s +search"
nmap <leader>ss :action FindInPath<cr>
let g:WhichKeyDesc_search_path = "<leader>ss search path"
nmap <leader>sa :action GotoAction<cr>
let g:WhichKeyDesc_search_action = "<leader>sa search action"
nmap <leader>sf :action GotoFile<cr>
let g:WhichKeyDesc_search_file = "<leader>sf search file"
nmap <leader>sc :action GotoClass<cr>
let g:WhichKeyDesc_search_class = "<leader>sc search class"
" TODO: Add search all?

" The next few blocks are window/buffer management. These are directly on leader instead of behind
" a prefix, because they are frequently used. Note that these all apply only to editor splits, not tool windows.

nmap <leader>\| :action SplitVertically<cr>
let g:WhichKeyDesc_split_vertically = "<leader>| split vertically"
nmap <leader>- :action SplitHorizontally<cr>
let g:WhichKeyDesc_split_horizontally = "<leader>- split horizontally"
nmap <leader>* :action ChangeSplitOrientation<cr>
let g:WhichKeyDesc_rotate = "<leader>* rotate splits"
nmap <leader>u :action Unsplit<cr>
let g:WhichKeyDesc_unsplit = "<leader>u unsplit"
nmap <leader>U :action UnsplitAll<cr>
let g:WhichKeyDesc_unsplitall = "<leader>U unsplit all"

nmap <leader>h :action TabShiftActions.MoveFocusLeft<cr>
let g:WhichKeyDesc_left = "<leader>h focus left"
nmap <leader>j :action TabShiftActions.MoveFocusDown<cr>
let g:WhichKeyDesc_down = "<leader>j focus down"
nmap <leader>k :action TabShiftActions.MoveFocusUp<cr>
let g:WhichKeyDesc_up = "<leader>k focus up"
nmap <leader>l :action TabShiftActions.MoveFocusRight<cr>
let g:WhichKeyDesc_right = "<leader>l focus right"

nmap <leader>H :action TabShiftActions.ShiftLeft<cr>
let g:WhichKeyDesc_move_left = "<leader>H move tab left"
nmap <leader>J :action TabShiftActions.ShiftDown<cr>
let g:WhichKeyDesc_move_down = "<leader>J move tab down"
nmap <leader>K :action TabShiftActions.ShiftUp<cr>
let g:WhichKeyDesc_move_up = "<leader>K move tab up"
nmap <leader>L :action TabShiftActions.ShiftRight<cr>
let g:WhichKeyDesc_move_right = "<leader>L move tab right"

nmap <leader>k :action CloseEditor<cr>
nmap <leader>K :action CloseEditor<cr>

" refactoring prefix
let g:WhichKeyDesc_refactor = "<leader>r +refactor"

nmap <leader>rr :action Refactorings.QuickListPopupAction<cr>
let g:WhichKeyDesc_refactor_popup = "<leader>rr popup"
nmap <leader>rR :action RenameElement<cr>
let g:WhichKeyDesc_refactor_rename = "<leader>rR rename"
nmap <leader>rf :action ShowIntentionActions<cr>
let g:WhichKeyDesc_refactor_fixit = "<leader>rf fixit"
nmap <leader>rs :action ChangeSignature<cr>
let g:WhichKeyDesc_refactor_signature = "<leader>rs change signature"
nmap <leader>rc :action CopyElement<cr>
let g:WhichKeyDesc_refactor_copy = "<leader>rc copy"
nmap <leader>rm :action Move<cr>
let g:WhichKeyDesc_refactor_move = "<leader>rm move"
nmap <leader>rd :action SafeDelete<cr>
let g:WhichKeyDesc_refactor_delete = "<leader>rd delete"
nmap <leader>r<Space> :action ReformatCode<cr>
let g:WhichKeyDesc_refactor_reformat = "<leader>r<Space> reformat"

" extract prefix. A type of refactoring, but it had enough bindings to warrant its own prefix
let g:WhichKeyDesc_extract = "<leader>e +extract"
map <leader>ev :action CIDR.Lang.IntroduceVariable<cr>
map <leader>ec :action CIDR.Lang.IntroduceConstant<cr>
map <leader>ep :action CIDR.Lang.IntroduceParameter<cr> map <leader>ed :action CIDR.Lang.IntroduceDefine<cr>
map <leader>et :action CIDR.Lang.IntroduceTypedef<cr>
map <leader>em :action ExtractMethod<cr>

" (code) generation prefix.
let g:WhichKeyDesc_generate = "<leader>g +generate"
nmap <leader>gg :action Generate<cr>
nmap <leader>go :action OverrideMethods<cr>
nmap <leader>gd :action CIDR.Lang.Cpp.GenerateDefinitions<cr>
nmap <leader>gc :action CIDR.Lang.Cpp.GenerateConstructor<cr>
nmap <leader>ge :action CIDR.Lang.Cpp.GenerateEqualityOperators<cr>
nmap <leader>gr :action CIDR.Lang.Cpp.GenerateRelationalOperators<cr>
nmap <leader>gs :action CIDR.Lang.Cpp.GenerateStreamOutputOperator<cr>
nmap <leader>gag :action CIDR.Lang.Cpp.GenerateGetter<cr>
nmap <leader>gas :action CIDR.Lang.Cpp.GenerateSetter<cr>
nmap <leader>gaa :action CIDR.Lang.Cpp.GenerateGetterAndSetter<cr>

" compile (build) prefix"
let g:WhichKeyDesc_compile = "<leader>c +compile"
nmap <leader>cc :action Build<cr>
nmap <leader>cC :action RunConfiguration<cr>
nmap <leader>cr :action Run<cr>
nmap <leader>ck :action StopBackgroundProcesses<cr>
nmap <leader>cR :action RunClass<cr>

" debug prefix"
let g:WhichKeyDesc_debug = "<leader>d +debug"
nmap <leader>dd :action Debug<cr>
nmap <leader>dD :action DebugClass<cr>
nmap <leader>db :action ToggleLineBreakpoint<cr>
nmap <leader>dp :action QuickEvaluateExpression<cr>
nmap <leader>ds :action StepInto<cr>
nmap <leader>dn :action StepOver<cr>
nmap <leader>dp :action StepOut<cr>
nmap <leader>dk :action Stop<cr>

" version control prefix (generally git, but g is taken for "generate", this could be changed though)
let g:WhichKeyDesc_vc = "<leader>v +version-control"
nmap <leader>va :action Annotate<cr>
```

**Comment by TheBlob42** [comment] 2021-11-25 07:08
This is probably not what you want to hear, but it works on my machine :see_no_evil: 

![which_key_erase_works_on_my_machine](https://user-images.githubusercontent.com/6849129/143395056-ffa41aba-b9c7-4a58-aac1-209bd4f18c99.png)

Here are some details about the setup I am using, maybe there is another difference? But since everything else regarding WhichKey works fine (I guess) this sounds super weird to me :thinking: 

```text
IntelliJ IDEA 2021.2.3 (Community Edition)
IdeaVim: 1.8.1
WhichKey: 0.6
```
Do you have any other IdeaVim specific plugins installed, which might mess with this (and which I might not have installed)? But I am running out of ideas...
